--- 

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure packages are installed.
  yum:
    package: "{{ item }}"
    state: present
  with_items: "{{ ansible_packages }}"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml "setup-{{ ansible_os_family }}.yml"
