--- 

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure packages are installed.
  package:
    package: "{{ item }}"
    state: present
  with_items: "{{ ansible_packages }}"

- stat: path=/tmp/ansible.all
  register: dump
- template: src=dumpall.j2 dest=/tmp/ansible.all
  when: dump.stat.exists == False

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
